package-name: TSR.Emission
visual-name: TSR Emission
destination-folder: Assets/VRLabs/Toony Standard Rebuild Modules/TSR Emission
extra-generated-meta:
  - path: Assets/VRLabs
    guid: 652a1ba5b00554143bc9a76307dbc4e8
  - path: Assets/VRLabs/Toony Standard Rebuild Modules
    guid: d3d02b5b274410849ba3e6c360e2f005
  - path: Assets/VRLabs/Toony Standard Rebuild Modules/TSR Emission
    guid: 5ca494356720e574091b6f779604c389